service: http-handler # NOTE: update this with your service name

plugins:
 - serverless-apigw-binary
 - serverless-offline

custom:
  apigwBinary:
    types:
      - 'image/jpeg'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: serverless-admin
  # profile: new_serverless

functions:
  upload:
    handler: handler.upload
    role: arn:aws:iam::226373140466:role/lambda-http-handler

    events:
     - http:
         path: images
         method: post

  get:
    handler: handler.get
    role: arn:aws:iam::364350264218:role/lambda-http-handler-get
    vpc: 
      subnetIds:
        - subnet-05adb3fea32fabfa6
      securityGroupIds:
        - sg-046e3b7066a0eadec

    events:
     - http:
         path: images
         method: get
         
